debug: true

messages:
  enabled: '§aenabled§f'
  disabled: '§cdisabled§f'
  permission: '§fYou are not an op or lack permission (§a%1$s.%2$s§f)'
  debug: '§f[DEBUG]: '
  NpcMod:
    prefix: '§9MobMod: §f'
    worlds: '§fWorlds with MobMod (§a%1$s§f)'
    currentzone: '§fYou are in the %1$s%2$s §fzone!'
    zone: '§fZone: %1$s%2$s'
    radius: '§fMax radius: §a%1$,.1f'
    

maxRadius: 1000.0

values:
  STONE: 1
  GRASS: 1
  DIRT: 1
  COBBLESTONE: 1
  WOOD: 32
  SAPLING: 32
  SAND: 1
  GRAVEL: 4
  LOG: 64
  LEAVES: 1
  LAPIS_ORE: 8
  WEB: 12
  DEAD_BUSH: 1
  YELLOW_FLOWER: 16
  RED_ROSE: 16
  MOSSY_COBBLESTONE: 145
  OBSIDIAN: 64
  SNOW: 1
  ICE: 1
  SNOW_BLOCK: 1
  CACTUS: 8
  PUMPKIN: 144
  NETHERRACK: 1
  SOUL_SAND: 49
  INK_SACK: 144
  REDSTONE: 64
  IRON_INGOT: 256
  GOLD_INGOT: 2048
  STICK: 4
  STRING: 12
  SULPHUR: 192
  DIAMOND: 8192
  EMERALD: 512
  COAL: 128
  CLAY_BALL: 16
  GLOWSTONE_DUST: 384
  MELON: 144
  FLINT: 4
  FEATHER: 48
  LEATHER: 64
  WHEAT: 24
  APPLE: 128
  SUGAR_CANE: 32
  EGG: 32
  BLAZE_ROD: 1536
  NETHER_BRICK: 4
  BROWN_MUSHROOM: 32
  RED_MUSHROOM: 32
  SLIME_BALL: 24
  CLAY_BRICK: 64
  SPIDER_EYE: 128
  MILK_BUCKET: 833
  ENDER_PEARL: 1024